### ISSUE TITLE
Yellorite not generated in the Mining Biome

### ISSUE THREAD

**Issue by bales75** [asim0v/GamealitionPack#3]
Have tried searching for yellorite with the digital miner but have been unable to find any in the mining biome.  It has definitely generated in the overworld, however.

**Comment by asim0v** [comment]
Huh, apparently dimensions in which yellorite ore will generate have to be explicitly defined in the Extreme Reactors config. Did not realize this. It will be fixed in the next update.

**Comment by bales75** [comment]
It doesn't appear to be generating from the Void Ore miner from Environmental Tech.  I'm trying to run a test right now to verify.

**Comment by bales75** [comment]
Yeah, Yellorite isn't listed on the ET Void Miner table, and after an hour, other than resonant ender, no Yellorite.

https://i.imgur.com/hn7BRR3.pngz

**Comment by asim0v** [comment]
This is a separate issue entirely and should have been its own report. Regardless, I went through the config and yellorite ore is definitely listed for the void ore miner. Are you by chance using the default lens? Because there are so many resources in the game, you'll probably need to use a yellow lens to increase your chances.
